import React,{useState,useEffect}  from 'react';
import {
  Button,
  Row,
  Table,
  Col,
} from 'reactstrap';
import { useLocation, useNavigate } from 'react-router-dom';
import Barcode from 'react-barcode';
import ComponentCard1 from '../../../components/ComponentCard1';
import ComponentCard4 from '../../../components/ComponentCard4';
import 'react-table-v6/react-table.css';
// import Barcode from "../../../assets/images/bg/barcode.png"
import ProductPairView from './ProductPairView';

const JumbotronComponent = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [data, setData] = useState([]);
  const [data9, setData9] = useState([]);

  const product = location.state.item;

  const {backSideProduct} = location.state;

  const SmallPrint = (dispatchItem)=>{
    console.log('hi',dispatchItem);
    navigate('/operations/small/print',{state: dispatchItem});
  }

  const gradeName  = (gradeId)=>{

    console.log('productprints',gradeId);

      const grade = data9.find((d)=> d.id === gradeId);
      
      console.log('grade',grade)
   
      return grade?.name

}


  console.log('product in view',product);

  const handleEditAdd = () => {
    navigate('/order/factory-surplus/edit',{state:{product, backSideProduct}});
  };

;

  const handleSmallRollEdit = (rollItem) => {
    navigate('/order/factory-surplus/small-roll-edit', {state: rollItem});
  };

  const handleDeleteClick = async (itemId) => {
    try {
      // Call your API endpoint to delete the item
      const token = localStorage.getItem('userToken');
      const response = await fetch(`https://factory.teamasia.in/api/public/smallrolls/${itemId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
  
      // Check if the request was successful
      if (!response.ok) {
        throw new Error(`Error: ${response.statusText}`);
      }
  
      // Filter out the deleted item from your data state
      const updatedData = data.filter((item) => item.id !== itemId);
      setData(updatedData);
  
      console.log('Item deleted successfully');
    } catch (error) {
      //only checks for error that are generated by fetch function , and cors 
      console.error('Failed to delete the item', error);
    }
  };

  useEffect(() => {
    const fetchData = async () => {
      const token = localStorage.getItem('userToken');
      // console.log('token',token);
      const response = await fetch(`https://factory.teamasia.in/api/public/smallrolls/?product_id=${product.id}`, {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      // console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      console.log("responsejson1",result.smallrolls);
      setData(result.smallrolls); 
    };


    const fetchData9 = async () => {
      const token = localStorage.getItem('userToken');
      // console.log('token',token);
      const response = await fetch('https://factory.teamasia.in/api/public/grades', {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      // console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      const resultX = result.grades.slice();
      resultX.push({ id: 'x', name: 'Choose' });
      setData9(resultX);
    };

    fetchData9();

    fetchData();
  },[]);

  return (
    <>
      <ComponentCard1 title="">
         <Row>
                <Col md="12">
                  <Button className='my-btn-color' style={{ marginBottom: '1rem',marginRight:'10px' }} onClick={() => handleEditAdd()}>
                    Edit Product
                  </Button>
                </Col>
                
              </Row>
           
             <ProductPairView productID={product?.id}/> 

            {data?.length !== 0 ? <ComponentCard4 title="">  
                      <Table responsive size="sm">
                        <thead>
                          
                          <tr>
                            <th scope="col">S. No.</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Grade</th>
                            <th scope="col">Weight</th>
                            <th scope="col">BIN</th>
                            <th scope="col">GSM(g/m2)</th>
                            <th scope="col">Code</th>
                            <th scope="col">Action</th>
                            <th scope="col">Comment</th>
                          
                          </tr>
                        </thead>
                        <tbody>
                            {
                              data.map((roll,index)=>{
                            return (
                                      <tr key={roll.id}>
                                          <td>{index}</td>
                                          <td>{roll.quantity}</td>
                                          <td>{gradeName(roll.grade_id)}</td>
                                          <td>{roll.weight}</td>
                                          <td>{roll.bin}</td>
                                          <td>{((roll.weight * 1000) / (roll.quantity * roll.width)).toFixed(2)}</td>
                                          {/* <td><img src={Barcode} alt='barcode'/></td> */}
                                          <td><td><Barcode value={`SMALL${roll.id}`} height={20} /></td></td>
                                          <td>
                                            <td ><Button onClick={()=>SmallPrint(roll?.id)}><i className="bi bi-printer-fill my-pen-color" /></Button></td>
                                            <td ><Button onClick={()=>handleSmallRollEdit(roll)}><i className="bi bi-pencil-fill my-eye-color"  /></Button></td>
                                            <td ><Button onClick={() => handleDeleteClick(roll?.id)}><i className="bi bi-trash-fill my-bell-color" /></Button></td>
                                          </td>
                                          <td>{roll.comment}</td>
                                        </tr>
                                 )
                              })
                            }
                        </tbody>
                      </Table>
              </ComponentCard4>: ''}
              
           
        
      </ComponentCard1>
    </>
  );
};

export default JumbotronComponent;
