import React,{ useState,useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

import {
  Button,
  Input,
  Label,
  Col,
  Row,
  Pagination, 
  PaginationItem, 
  PaginationLink,
} from 'reactstrap';

import ComponentCard from '../../../components/ComponentCard5';

const Countries = () => {
  const navigate = useNavigate();
  const [data, setData] = useState([]);
  const [istrashed, setIstrashed] = useState('0');
  const [currentPage, setCurrentPage] = useState(1); // Track the current page
  const [totalPages, setTotalPages] = useState(1); // Track the total number of pages
  const itemsPerPage = 10; // Adjust this to the number of items per page

  const tableStyle = {
    
  };
  const handleEditClick = (item) => {
   
    navigate('/resources/countries/edit', { state: item});
  };

  const handleEditAdd = () => {
   
    navigate('/resources/countries/add');
  };
  const handleTrash = ()=>{
     
    if(istrashed === '0')
    {
      setIstrashed('1')
    }
    else{
      setIstrashed('0')
    }
  }
  const handleDeleteClick = async (itemId) => {
    try {
      // Call your API endpoint to delete the item
      const token = localStorage.getItem('userToken');
      const response = await fetch(`https://factory.teamasia.in/api/public/countries/${itemId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
  
      // Check if the request was successful
      if (!response.ok) {
        throw new Error(`Error: ${response.statusText}`);
      }
  
      // Filter out the deleted item from your data state
      const updatedData = data.filter((item) => item.id !== itemId);
      setData(updatedData);
  
      console.log('Item deleted successfully');
    } catch (error) {
      //only checks for error that are generated by fetch function , and cors 
      console.error('Failed to delete the item', error);
    }
  };
  
  const handlePageChange = (page) => {
    console.log(itemsPerPage);
    setCurrentPage(page);
  };


  const generatePaginationItems = () => {
    const items = [];
    const firstPage = 1;
    const lastPage = totalPages;
    console.log('currentPage',currentPage);
    // First and previous buttons
    items.push(
      <PaginationItem disabled={currentPage === firstPage} key="first">
        <PaginationLink first onClick={() => handlePageChange(firstPage)} />
      </PaginationItem>
    );
  
    items.push(
      <PaginationItem disabled={currentPage === firstPage} key="prev">
        <PaginationLink previous onClick={() => handlePageChange(currentPage - 1)} />
      </PaginationItem>
    );
  
    // Always show the first two pages
    items.push(
      <PaginationItem active={firstPage === currentPage} key={firstPage}>
        <PaginationLink onClick={() => handlePageChange(firstPage)}>{firstPage}</PaginationLink>
      </PaginationItem>
    );
  
    if (totalPages >= 2) {
      items.push(
        <PaginationItem active={currentPage === 2} key={2}>
          <PaginationLink onClick={() => handlePageChange(2)}>{2}</PaginationLink>
        </PaginationItem>
      );
    }
  
    // Show ellipsis (...) if there is a gap between the second and current page range
    if (currentPage > 4) {
      items.push(
        <PaginationItem key="ellipsis1" disabled>
          <PaginationLink>...</PaginationLink>
        </PaginationItem>
      );
    }
  
    // Pages around the current page
    for (let i = Math.max(3, currentPage - 1); i <= Math.min(currentPage + 1, totalPages - 2); i++) {
      items.push(
        <PaginationItem active={i === currentPage} key={i}>
          <PaginationLink onClick={() => handlePageChange(i)}>{i}</PaginationLink>
        </PaginationItem>
      );
    }
  
    // Show ellipsis (...) if there is a gap between the current page range and the second last page
    if (currentPage < totalPages - 3) {
      items.push(
        <PaginationItem key="ellipsis2" disabled>
          <PaginationLink>...</PaginationLink>
        </PaginationItem>
      );
    }
  
    // Always show the second last and last page
    if (totalPages - 1 > 2) {
      items.push(
        <PaginationItem active={totalPages - 1 === currentPage} key={totalPages - 1}>
          <PaginationLink onClick={() => handlePageChange(totalPages - 1)}>{totalPages - 1}</PaginationLink>
        </PaginationItem>
      );
    }
  
    items.push(
      <PaginationItem active={lastPage === currentPage} key={lastPage}>
        <PaginationLink onClick={() => handlePageChange(lastPage)}>{lastPage}</PaginationLink>
      </PaginationItem>
    );
  
    // Next and last buttons
    items.push(
      <PaginationItem disabled={currentPage === lastPage} key="next">
        <PaginationLink next onClick={() => handlePageChange(currentPage + 1)} />
      </PaginationItem>
    );
  
    items.push(
      <PaginationItem disabled={currentPage === lastPage} key="last">
        <PaginationLink last onClick={() => handlePageChange(lastPage)} />
      </PaginationItem>
    );
  
    return items;
  };

  

  useEffect(() => {
    
    // Fetch the data from the API
    const fetchData = async () => {
      const token = localStorage.getItem('userToken');
      console.log('token',token);
      const response = await fetch(`https://factory.teamasia.in/api/public/countries/?page=${currentPage}&limit=${itemsPerPage}&title=name&order=asc`, {
        method: 'GET', 
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      console.log('result',response);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      console.log("responsejson in country",result);
      if(result.countries){
        result.countries.sort((a, b) => {
           return a.name.localeCompare(b.name, undefined, { sensitivity: 'base' });
        });
      }
      setData(result.countries);
      setTotalPages(Math.ceil(result.numOfRows / 10));
    };
  
    fetchData();
  }, [istrashed,currentPage]);

  return (
    <ComponentCard
    title=""
    subtitle={
      <p>
        {/* Overview of the projects */}
      </p>
    }
  >
    <Row>
      <Col md="8">
        <Button className='my-btn-color' style={{ marginBottom: '1rem',marginRight:'10px' }} onClick={() => handleEditAdd()}>
          Add Country
        </Button>
      </Col>
      <Col md="4" className='p-2'>
          <Input  type="checkbox" style={{marginRight:'5px'}} onClick={()=> handleTrash()}/>
          <Label style={{fontWeight:'500'}}>Show Trashed Items</Label>
      </Col>
    </Row>

    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
      <table className="table" style={tableStyle}>
              <thead>
              <tr>
            <th>Country Name</th>
            <th>Actions</th>
          </tr>
              </thead>
              <tbody>
                {data.map((product) => (
                  <tr key={product.id}>
                  <td>{product.name}</td>
                 
                  <td>
                    {/* Action buttons or icons */}
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleEditClick(product)}><i className="bi bi-pencil-fill my-pen-color" /></button>
                      <button type="button" className="btn mybtncustomer btn-secondary btn-sm mr-2" onClick={() => handleDeleteClick(product.id)}><i className="bi bi-trash-fill my-trash-color" /></button>
                  </td>
                </tr>
                ))}
              </tbody>
            </table>
            
    </div>
   
    {
    totalPages>1?<div style={{ display: 'flex', justifyContent: 'flex-end' }}>
          <Pagination aria-label="Page navigation example">
            {generatePaginationItems()}
          </Pagination>
      </div>:null
   }
   
  </ComponentCard>

   
   
  );
};

export default Countries;